### ISSUE TITLE
Is there a way to enable video streaming in HD ?

### ISSUE THREAD

**Issue by qwert789** [Parrot-Developers/libARController#1]
I want to get live video in HD from bebop 2 is there a way to enable it?
Currently the quality is really bad.

**Comment by N-Bz** [comment]
Hi,

No, there is currently no way to force the drone into higher resolution streaming, mainly due to restrictions in the video encoder and the priority given to the recorded video.

On a side note, questions about the SDK should be asked on the [developer forum](http://forum.developer.parrot.com/), and not in github issues ;)

Regards,
Nicolas.
